'use client'
import { useCallback, useEffect, useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { SectionHeader } from './papers-section'
import { SCENARIO_TEMPLATES, type ScenarioType } from '@/lib/inet/scenarios'
import { Activity, CheckCircle2, Loader2, Network, Play, RefreshCw, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'

type Run = { id?: string; scenario?: string; status?: string; createdAt?: string; durationMs?: number }
export function InetLabSection() {
  const [scenario, setScenario] = useState<ScenarioType>('b5g-mesh'); const [runs, setRuns] = useState<Run[]>([])
  const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false); const [checking, setChecking] = useState(false); const [error, setError] = useState<string | null>(null); const [dependency, setDependency] = useState<string | null>(null)
  const template = SCENARIO_TEMPLATES[scenario]
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch('/api/inet/runs?limit=10'); if (!r.ok) throw new Error('加载运行记录失败'); const d = await r.json(); setRuns(Array.isArray(d) ? d : d.runs ?? []) } catch (e) { setError((e as Error).message) } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  const check = async () => { setChecking(true); try { const r = await fetch('/api/inet/dependencies'); const d = await r.json(); setDependency(d.status ?? (r.ok ? '依赖可用' : '依赖检查失败')) } catch { setDependency('依赖检查失败') } finally { setChecking(false) } }
  const run = async () => { setRunning(true); setError(null); try { const r = await fetch('/api/inet/runs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario, parameters: template.parameters }) }); if (!r.ok) throw new Error((await r.json()).error ?? '运行失败'); toast.success('INET 场景运行已提交'); await load() } catch (e) { setError((e as Error).message); toast.error((e as Error).message) } finally { setRunning(false) } }
  return <div className="space-y-6"><SectionHeader icon={Network} title="智能组网实验室" desc="选择 INET 场景，检查运行依赖并提交可复现实验。" /><div className="grid gap-6 lg:grid-cols-[380px_1fr]"><Card className="h-fit"><CardHeader><CardTitle>场景配置</CardTitle><CardDescription>预置参数可直接运行</CardDescription></CardHeader><CardContent className="space-y-4"><Select value={scenario} onValueChange={v => setScenario(v as ScenarioType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.values(SCENARIO_TEMPLATES).map(s => <SelectItem key={s.type} value={s.type}>{s.name}</SelectItem>)}</SelectContent></Select><p className="text-sm text-muted-foreground">{template.description}</p><div className="rounded-md border p-3 text-xs space-y-1"><div className="font-medium">参数摘要</div><div>节点数：{(template.parameters.topology as { nodeCount: number }).nodeCount}</div><div>频率：{(template.parameters.radio as { frequencyGHz: number }).frequencyGHz} GHz</div><div>指标：{template.metrics.join(' · ')}</div></div><div className="flex gap-2"><Button variant="outline" onClick={check} disabled={checking}>{checking ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ShieldCheck className="mr-2 h-4 w-4" />}检查依赖</Button><Button onClick={run} disabled={running}>{running ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}运行场景</Button></div>{dependency && <Badge variant="secondary"><CheckCircle2 className="mr-1 h-3 w-3" />{dependency}</Badge>}{error && <p className="text-sm text-destructive">{error}</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center justify-between">最近运行 <Button size="icon" variant="ghost" onClick={load} aria-label="刷新"><RefreshCw className="h-4 w-4" /></Button></CardTitle></CardHeader><CardContent>{loading ? <div className="flex items-center gap-2 text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />加载中</div> : runs.length === 0 ? <div className="py-10 text-center text-muted-foreground"><Activity className="mx-auto mb-2 h-8 w-8" />暂无运行记录</div> : <div className="space-y-2">{runs.map((r, i) => <div key={r.id ?? i} className="flex items-center justify-between rounded-md border p-3 text-sm"><span>{SCENARIO_TEMPLATES[r.scenario as ScenarioType]?.name ?? r.scenario ?? 'INET 场景'}</span><Badge variant="outline">{r.status ?? 'completed'}</Badge></div>)}</div>}</CardContent></Card></div></div>
}
