'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Sparkles, Copy, Loader2, FileText, Globe, Languages } from 'lucide-react'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'

export function AIReviewGenerator() {
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<string | null>(null)
  const [topic, setTopic] = useState('')
  const [focus, setFocus] = useState('general')
  const [language, setLanguage] = useState('zh')

  const generate = async () => {
    if (!topic.trim()) {
      toast.error('请输入研究课题')
      return
    }
    setLoading(true)
    setResult(null)
    try {
      const res = await fetch('/api/ai-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic, focus, language }),
      })
      const data = await res.json()
      if (data.success) {
        setResult(data.content)
        toast.success('文献综述已生成')
      } else {
        toast.error(data.error || '生成失败')
      }
    } catch (e) {
      toast.error('AI 生成失败: ' + (e as Error).message)
    } finally {
      setLoading(false)
    }
  }

  const copy = () => {
    if (!result) return
    navigator.clipboard.writeText(result)
    toast.success('已复制到剪贴板')
  }

  const copyAsMarkdown = () => {
    if (!result) return
    // Copy as .md file content
    const md = `# 文献综述: ${topic}\n\n${result}\n\n---\n*Generated by AI 通信组网科研助手*`
    navigator.clipboard.writeText(md)
    toast.success('已复制为 Markdown 格式')
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-sm flex items-center gap-2">
              <FileText className="h-4 w-4 text-primary" />
              AI 文献综述生成器
            </CardTitle>
            <CardDescription className="text-xs">
              基于论文库 · AI 自动生成结构化文献综述（含 Research Gap）
            </CardDescription>
          </div>
          <Badge variant="outline" className="text-[9px] bg-primary/5">
            <Sparkles className="h-2.5 w-2.5 mr-0.5" />
            LLM
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {/* Input form */}
        <div>
          <Label className="text-xs">研究课题 *</Label>
          <Input
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="例如: RIS 辅助网络中的 DRL 资源分配"
            className="mt-1 text-xs"
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <Label className="text-xs">综述重点</Label>
            <Select value={focus} onValueChange={setFocus}>
              <SelectTrigger className="h-8 text-xs mt-1"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="general">综合（方法分类+Gap）</SelectItem>
                <SelectItem value="method">方法对比</SelectItem>
                <SelectItem value="gap">研究空白</SelectItem>
                <SelectItem value="timeline">时间脉络</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label className="text-xs">输出语言</Label>
            <Select value={language} onValueChange={setLanguage}>
              <SelectTrigger className="h-8 text-xs mt-1"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="zh">中文</SelectItem>
                <SelectItem value="en">English</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Generate button */}
        <Button
          onClick={generate}
          disabled={loading || !topic.trim()}
          className="w-full"
          size="sm"
        >
          {loading ? (
            <><Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> AI 生成中（约 30 秒）...</>
          ) : (
            <><Sparkles className="h-3.5 w-3.5 mr-1.5" /> 生成文献综述</>
          )}
        </Button>

        {/* Result */}
        {result && (
          <div className="rounded-md border border-primary/20 bg-primary/5 p-3 animate-fade-in">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-1.5">
                <FileText className="h-3.5 w-3.5 text-primary" />
                <span className="text-xs font-medium text-primary">AI 生成结果</span>
                <Badge variant="secondary" className="text-[9px]">
                  {language === 'zh' ? '中文' : 'English'}
                </Badge>
                <Badge variant="secondary" className="text-[9px]">
                  {focus === 'general' ? '综合' : focus === 'method' ? '方法对比' : focus === 'gap' ? '研究空白' : '时间脉络'}
                </Badge>
              </div>
              <div className="flex gap-1">
                <button
                  onClick={copy}
                  className="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-foreground"
                >
                  <Copy className="h-2.5 w-2.5" /> 复制
                </button>
                <button
                  onClick={copyAsMarkdown}
                  className="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-foreground"
                >
                  <FileText className="h-2.5 w-2.5" /> MD
                </button>
              </div>
            </div>
            <pre className="text-xs leading-relaxed whitespace-pre-wrap font-sans max-h-[500px] overflow-y-auto">
              {result}
            </pre>
          </div>
        )}

        {/* Tip */}
        {!result && !loading && (
          <div className="text-center text-[10px] text-muted-foreground py-1">
            💡 方法论 §2.4 文献综述产出 · 综述 = 分类 + 对比 + 指出 Gap
          </div>
        )}
      </CardContent>
    </Card>
  )
}
